FIND_PATH(OPENVR_INCLUDE_DIR "openvr.h"
			$ENV{OPENVR_DIR}/include
			NO_DEFAULT_PATH
)

MACRO(FIND_OPENVR_LIBRARY MYLIBRARY MYLIBRARYNAME)
	
	# FIND_LIBRARY(${MYLIBRARY} ${MYLIBRARYNAME} $ENV{OSG_DIR} ${BUILD})
FIND_LIBRARY(     ${MYLIBRARY}
          NAMES       ${MYLIBRARYNAME}
          PATHS
          $ENV{OPENVR_DIR}/lib
      NO_DEFAULT_PATH
      )
	  message("path: " ${MYLIBRARY})
ENDMACRO(FIND_OPENVR_LIBRARY )

# Find release (optimized) libs
FIND_OPENVR_LIBRARY(OPENVR_LIBRARY openvr_api)

SET(OPENVR_FOUND "NO")
IF(OPENVR_LIBRARY AND OPENVR_INCLUDE_DIR)
    SET(OPENVR_FOUND "YES")
ENDIF(OPENVR_LIBRARY AND OPENVR_INCLUDE_DIR)
