FIND_PATH(OSGOPENVR_INCLUDE_DIR "openvrviewer.h"
			$ENV{OSGOPENVR_DIR}/include
			NO_DEFAULT_PATH
)

MACRO(FIND_OSGOPENVR_LIBRARY MYLIBRARY MYLIBRARYNAME)
	
	# FIND_LIBRARY(${MYLIBRARY} ${MYLIBRARYNAME} $ENV{OSG_DIR} ${BUILD})
FIND_LIBRARY(     ${MYLIBRARY}
          NAMES       ${MYLIBRARYNAME}
          PATHS
          $ENV{OSGOPENVR_DIR}/lib
      NO_DEFAULT_PATH
      )
	  message("path: " ${MYLIBRARY})
ENDMACRO(FIND_OSGOPENVR_LIBRARY )

# Find release (optimized) libs
FIND_OSGOPENVR_LIBRARY(OSGOPENVR_LIBRARY OsgOpenVR)
FIND_OSGOPENVR_LIBRARY(OSGOPENVR_LIBRARY_DEBUG OsgOpenVRd)

SET(OPENVR_FOUND "NO")
IF(OPENVR_LIBRARY AND OPENVR_INCLUDE_DIR)
    SET(OPENVR_FOUND "YES")
ENDIF(OPENVR_LIBRARY AND OPENVR_INCLUDE_DIR)
