FIND_PATH(OSG_INCLUDE_DIR osg/Node
			
			$ENV{OSG_DIR}/include
			NO_DEFAULT_PATH
)

MACRO(FIND_OSG_LIBRARY MYLIBRARY MYLIBRARYNAME)
	
	# FIND_LIBRARY(${MYLIBRARY} ${MYLIBRARYNAME} $ENV{OSG_DIR} ${BUILD})
FIND_LIBRARY(     ${MYLIBRARY}
          NAMES       ${MYLIBRARYNAME}
          PATHS
          $ENV{OSG_DIR}/lib
      NO_DEFAULT_PATH
      )
	  message("path: " ${MYLIBRARY})
ENDMACRO(FIND_OSG_LIBRARY )

# Find release (optimized) libs
FIND_OSG_LIBRARY(OSG_LIBRARY 						osg 				)
FIND_OSG_LIBRARY(OSGUTIL_LIBRARY 					osgUtil 			)
FIND_OSG_LIBRARY(OSGDB_LIBRARY 						osgDB 				)
FIND_OSG_LIBRARY(OSGTEXT_LIBRARY 					osgText 			)
FIND_OSG_LIBRARY(OSGTERRAIN_LIBRARY 				osgTerrain 			)
FIND_OSG_LIBRARY(OSGFX_LIBRARY 						osgFX 				)
FIND_OSG_LIBRARY(OSGVIEWER_LIBRARY 					osgViewer 			)
FIND_OSG_LIBRARY(OSGGA_LIBRARY 						osgGA 				)
FIND_OSG_LIBRARY(OSGPARTICLE_LIBRARY 				osgParticle 		)
FIND_OSG_LIBRARY(OSGSIM_LIBRARY 					osgSim 				)
FIND_OSG_LIBRARY(OSGSHADOW_LIBRARY 					osgShadow 			)
FIND_OSG_LIBRARY(OPENTHREADS_LIBRARY 				OpenThreads 		)
FIND_OSG_LIBRARY(OSGMANIPULATOR_LIBRARY 			osgManipulator 		)
FIND_OSG_LIBRARY(OSGANIMATION_LIBRARY 				osgAnimation 		)
FIND_OSG_LIBRARY(OSGQT_LIBRARY 						osgQt 				)

# Find debug libs
FIND_OSG_LIBRARY(OSG_LIBRARY_DEBUG 					osgd 				)
FIND_OSG_LIBRARY(OSGUTIL_LIBRARY_DEBUG 				osgUtild 			)
FIND_OSG_LIBRARY(OSGDB_LIBRARY_DEBUG 				osgDBd 				)
FIND_OSG_LIBRARY(OSGTEXT_LIBRARY_DEBUG 				osgTextd 			)
FIND_OSG_LIBRARY(OSGTERRAIN_LIBRARY_DEBUG 			osgTerraind 		)
FIND_OSG_LIBRARY(OSGFX_LIBRARY_DEBUG 				osgFXd 				)
FIND_OSG_LIBRARY(OSGVIEWER_LIBRARY_DEBUG 			osgViewerd 			)
FIND_OSG_LIBRARY(OSGGA_LIBRARY_DEBUG 				osgGAd 				)
FIND_OSG_LIBRARY(OSGPARTICLE_LIBRARY_DEBUG 			osgParticled 		)
FIND_OSG_LIBRARY(OSGSIM_LIBRARY_DEBUG 				osgSimd 			)
FIND_OSG_LIBRARY(OSGSHADOW_LIBRARY_DEBUG 			osgShadowd 			)
# FIND_OSG_LIBRARY(OSGTUIO_LIBRARY_DEBUG 				osgTUIOd 			debug)
FIND_OSG_LIBRARY(OPENTHREADS_LIBRARY_DEBUG 			OpenThreadsd 		)
FIND_OSG_LIBRARY(OSGMANIPULATOR_LIBRARY_DEBUG 		osgManipulatord 	)
FIND_OSG_LIBRARY(OSGANIMATION_LIBRARY_DEBUG			osgAnimationd		)
FIND_OSG_LIBRARY(OSGQT_LIBRARY_DEBUG 				osgQtd 				)

SET(OSG_FOUND "NO")
IF(OSG_LIBRARY AND OSG_INCLUDE_DIR)
    SET(OSG_FOUND "YES")
ENDIF(OSG_LIBRARY AND OSG_INCLUDE_DIR)
