
# Created By Lokesh Sharma
FIND_PATH( VRPN_INCLUDE_DIR "vrpn_Configure.h"
    $ENV{VRPN_DIR}/include
    NO_DEFAULT_PATH
)

MACRO(FIND_VRPN_LIBRARY MYLIBRARY MYLIBRARYNAME)
	
	# FIND_LIBRARY(${MYLIBRARY} ${MYLIBRARYNAME} $ENV{OSG_DIR} ${BUILD})
FIND_LIBRARY(     ${MYLIBRARY}
          NAMES       ${MYLIBRARYNAME}
          PATHS
          $ENV{VRPN_DIR}/lib
      NO_DEFAULT_PATH
      )
	  message("path: " ${MYLIBRARY})
ENDMACRO(FIND_VRPN_LIBRARY )

FIND_VRPN_LIBRARY(VRPN_LIBRARY vrpn)
FIND_VRPN_LIBRARY(QUAT_LIBRARY quat)

FIND_VRPN_LIBRARY(QUAT_LIBRARY_DEBUG quatd)
FIND_VRPN_LIBRARY(VRPN_LIBRARY_DEBUG vrpnd)