
# Created By Lokesh Sharma
FIND_PATH( TRANS_VIZ_INCLUDE_DIR "TransVizUtil.h"
    $ENV{TRANSVIZ_DIR}/include
    NO_DEFAULT_PATH
)

MACRO(FIND_TRANSVIZ_LIBRARY MYLIBRARY MYLIBRARYNAME)
	
	# FIND_LIBRARY(${MYLIBRARY} ${MYLIBRARYNAME} $ENV{OSG_DIR} ${BUILD})
FIND_LIBRARY(     ${MYLIBRARY}
          NAMES       ${MYLIBRARYNAME}
          PATHS
          $ENV{TRANSVIZ_DIR}/lib
      NO_DEFAULT_PATH
      )
ENDMACRO(FIND_TRANSVIZ_LIBRARY )

FIND_TRANSVIZ_LIBRARY(TRANSVIZ_UTIL_LIBRARY TransVizUtil)