
# Created By Lokesh Sharma
FIND_PATH( TINYXML_INCLUDE_DIR "tinyxml2.h"
    $ENV{TINYXML_DIR}/include
    NO_DEFAULT_PATH
)

MACRO(FIND_TINYXML_LIBRARY MYLIBRARY MYLIBRARYNAME)
	
	# FIND_LIBRARY(${MYLIBRARY} ${MYLIBRARYNAME} $ENV{OSG_DIR} ${BUILD})
FIND_LIBRARY(     ${MYLIBRARY}
          NAMES       ${MYLIBRARYNAME}
          PATHS
          $ENV{TINYXML_DIR}/lib
      NO_DEFAULT_PATH
      )
	  message("path: " ${MYLIBRARY})
ENDMACRO(FIND_TINYXML_LIBRARY )

FIND_TINYXML_LIBRARY(TINYXML_LIBRARY tinyxml2d)